echo "max"
python3 main.py --exp_name noise_rot --eval True --sigma 0.001 --aggregation 'max' --model_path 'checkpoints/K20/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --sigma 0.005 --aggregation 'max' --model_path 'checkpoints/K20/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --sigma 0.01 --aggregation 'max' --model_path 'checkpoints/K20/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --sigma 0.05 --aggregation 'max' --model_path 'checkpoints/K20/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --sigma 0.1 --aggregation 'max' --model_path 'checkpoints/K20/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --sigma 0.5 --aggregation 'max' --model_path 'checkpoints/K20/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --sigma 1 --aggregation 'max' --model_path 'checkpoints/K20/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --sigma 5 --aggregation 'max' --model_path 'checkpoints/K20/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --sigma 10 --aggregation 'max' --model_path 'checkpoints/K20/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --sigma 50 --aggregation 'max' --model_path 'checkpoints/K20/models/model.t7'
echo "mean"
python3 main.py --exp_name noise_rot --eval True --sigma 0.001 --aggregation 'mean' --model_path 'checkpoints/K20_mean/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --sigma 0.005 --aggregation 'mean' --model_path 'checkpoints/K20_mean/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --sigma 0.01 --aggregation 'mean' --model_path 'checkpoints/K20_mean/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --sigma 0.05 --aggregation 'mean' --model_path 'checkpoints/K20_mean/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --sigma 0.1 --aggregation 'mean' --model_path 'checkpoints/K20_mean/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --sigma 0.5 --aggregation 'mean' --model_path 'checkpoints/K20_mean/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --sigma 1 --aggregation 'mean' --model_path 'checkpoints/K20_mean/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --sigma 5 --aggregation 'mean' --model_path 'checkpoints/K20_mean/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --sigma 10 --aggregation 'mean' --model_path 'checkpoints/K20_mean/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --sigma 50 --aggregation 'mean' --model_path 'checkpoints/K20_mean/models/model.t7'
echo "mean"
python3 main.py --exp_name noise_rot --eval True --angle 1.6 --aggregation 'max' --model_path 'checkpoints/K20/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --angle 3.14 --aggregation 'max' --model_path 'checkpoints/K20/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --angle 4.71 --aggregation 'max' --model_path 'checkpoints/K20/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --angle 5 --aggregation 'max' --model_path 'checkpoints/K20/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --angle 1.6 --aggregation 'mean' --model_path 'checkpoints/K20_mean/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --angle 3.14 --aggregation 'mean' --model_path 'checkpoints/K20_mean/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --angle 4.71 --aggregation 'mean' --model_path 'checkpoints/K20_mean/models/model.t7'
python3 main.py --exp_name noise_rot --eval True --angle 5 --aggregation 'mean' --model_path 'checkpoints/K20_mean/models/model.t7'
